# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-02-10 15:02
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_image'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userprofile',
            managers=[
                ('dublin', django.db.models.manager.Manager()),
            ],
        ),
    ]
