# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-03-18 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190210_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='description',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='image',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='website',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Age',
            field=models.CharField(default='18-24', max_length=50, verbose_name='age'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Gender',
            field=models.CharField(default='M', max_length=5, verbose_name='gender'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Occupation',
            field=models.CharField(default='other', max_length=100, verbose_name='job'),
        ),
    ]
