# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-03-19 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20190319_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='Age',
            field=models.CharField(choices=[('Under18', 'Under18'), ('18-24', '18-24'), ('25-34', '25-34'), ('35-44', '35-44'), ('45-49', '45-49'), ('50-55', '50-55'), ('56+', '56+')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='Gender',
            field=models.CharField(choices=[('F', 'F'), ('M', 'M'), ('O', 'O')], max_length=20),
        ),
    ]
