# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-03-19 23:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20190319_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='Gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('O', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='Occupation',
            field=models.CharField(choices=[('K-12student', 'K-12student'), ('self-employed', 'Self Employed'), ('scientist', 'Scientist'), ('executive/managerial', 'Executive or Managerial'), ('writer', 'Writer'), ('homemaker', 'Home maker'), ('academic/educator', 'Academic or educator'), ('scientist', 'Scientist'), ('doctor/health care', 'Doctor or Health care'), ('sales/marketing', 'Sales or Marketing'), ('clerical/admin', 'Clerical or Admin'), ('programmer', 'Programmer'), ('technician/engineer', 'Technician or Engineer'), ('college/grad student', 'College or Grad student'), ('artist', 'Artist'), ('tradesman/craftsman', 'Tradesman or Craftsman'), ('retired', 'Retired'), ('unemployed', 'Unemployed'), ('other', 'Other')], max_length=20),
        ),
    ]
