# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-04-09 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_addfriend_current_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='movie_name',
            field=models.CharField(default='Not available', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='post',
            field=models.CharField(max_length=1000),
        ),
    ]
