# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-03-12 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20190311_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='tmdbId',
            field=models.IntegerField(default=1, verbose_name='id'),
        ),
        migrations.AddField(
            model_name='topmovies',
            name='tmdbId',
            field=models.IntegerField(default=1, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='topmovies',
            name='rating',
            field=models.FloatField(default=3, verbose_name='rating'),
        ),
    ]
