# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-03-15 19:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20190312_1757'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDemographics',
            fields=[
                ('userId', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('Gender', models.CharField(default='M', max_length=2, verbose_name='gender')),
                ('Age', models.CharField(default='18-24', max_length=50, verbose_name='age')),
                ('Occupation', models.CharField(default='other', max_length=100, verbose_name='job')),
            ],
        ),
        migrations.CreateModel(
            name='UserRatings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=2, verbose_name='id')),
                ('tmdbId', models.IntegerField(default=1, verbose_name='id')),
                ('movieId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Movie')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.UserDemographics')),
            ],
        ),
    ]
