# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-03-17 19:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_auto_20190317_1917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userratings',
            old_name='movie_id_id',
            new_name='movie_id',
        ),
    ]
