# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-03-18 11:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_auto_20190317_1918'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userratings',
            old_name='userId_id',
            new_name='userId',
        ),
    ]
