# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-03-18 11:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_auto_20190318_1146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userratings',
            old_name='userId',
            new_name='userId_id',
        ),
    ]
