# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-03-18 12:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_auto_20190318_1159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdemographics',
            old_name='userId',
            new_name='userdemo_id',
        ),
        migrations.RenameField(
            model_name='userratings',
            old_name='movie_id',
            new_name='movie',
        ),
        migrations.RenameField(
            model_name='userratings',
            old_name='userId',
            new_name='userdemo',
        ),
    ]
