# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-03-18 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_auto_20190318_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='userratings',
            name='tmdbId',
            field=models.IntegerField(default=1, verbose_name='TmdbId'),
        ),
    ]
