# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-03-18 12:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0014_userratings_tmdbid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userratings',
            name='movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.Movie'),
        ),
    ]
