# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-03-18 13:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0016_auto_20190318_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userratings',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Movie'),
        ),
        migrations.AlterField(
            model_name='userratings',
            name='userdemo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.UserDemographics'),
        ),
    ]
