# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-03-18 13:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0017_auto_20190318_1307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topmovies',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='topmovies',
            name='title',
        ),
        migrations.RemoveField(
            model_name='topmovies',
            name='tmdbId',
        ),
    ]
