# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-03-18 13:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0018_auto_20190318_1312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userratings',
            old_name='movie',
            new_name='movie_id',
        ),
        migrations.RenameField(
            model_name='userratings',
            old_name='userdemo',
            new_name='userdemo_id',
        ),
    ]
