# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-03-18 13:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0019_auto_20190318_1317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userratings',
            old_name='userdemo_id',
            new_name='userdemo',
        ),
    ]
