# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-03-18 13:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0020_auto_20190318_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userratings',
            name='userdemo',
        ),
    ]
