# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-03-18 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0021_remove_userratings_userdemo'),
    ]

    operations = [
        migrations.AddField(
            model_name='topmovies',
            name='genre',
            field=models.CharField(default='', max_length=300, verbose_name='genres'),
        ),
        migrations.AddField(
            model_name='topmovies',
            name='title',
            field=models.CharField(default='N/A', max_length=300, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='topmovies',
            name='tmdbId',
            field=models.IntegerField(default=1, verbose_name='id'),
        ),
    ]
