# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-03-18 17:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0022_auto_20190318_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='userratings',
            name='userdemo_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='movies.UserDemographics'),
        ),
    ]
