# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-03-22 18:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0024_auto_20190322_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userratings',
            name='userdemo_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.UserProfile'),
        ),
    ]
