# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-03-22 18:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0025_auto_20190322_1853'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userratings',
            old_name='userdemo_id',
            new_name='user_id',
        ),
    ]
