# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-03-23 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0026_auto_20190322_1855'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userratings',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='userratings',
            name='rating',
            field=models.FloatField(choices=[(5, '10/10'), (4.5, '9/10'), (4, '8/10'), (3.5, '7/10'), (3, '6/10'), (2.5, '5/10'), (2, '4/10'), (1.5, '3/10'), (1, '2/10'), (0.5, '1/10')], default=2.5),
        ),
    ]
