# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-03-23 15:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0027_auto_20190323_1405'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userratings',
            old_name='movie_id',
            new_name='movie',
        ),
    ]
