# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-03-23 15:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20190319_2324'),
        ('movies', '0028_auto_20190323_1514'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userratings',
            unique_together=set([('user', 'movie')]),
        ),
    ]
