# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-03-27 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0031_auto_20190327_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupusers',
            name='group_name',
            field=models.CharField(default='hello', max_length=50, unique=True, verbose_name='name'),
        ),
    ]
