# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-03-27 18:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0032_groupusers_group_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupusers',
            name='group_name',
        ),
    ]
