# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-03-27 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0034_auto_20190327_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupusers',
            name='user_name',
            field=models.CharField(default='jane doe', max_length=100, verbose_name='name'),
        ),
    ]
