# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-03-31 21:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20190327_1517'),
        ('movies', '0035_groupusers_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMovieList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.GroupInfo')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.UserProfile')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='groupmovielist',
            unique_together=set([('movie', 'group')]),
        ),
    ]
