# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-04-03 12:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0040_auto_20190403_1324'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='watchlist',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='user',
        ),
        migrations.DeleteModel(
            name='WatchList',
        ),
    ]
