# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-04-05 00:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0041_auto_20190403_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmovielist',
            name='vote',
            field=models.IntegerField(default=0, verbose_name='Vote'),
        ),
    ]
