# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-04-05 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0043_auto_20190405_0241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmovielist',
            name='vote_dislikes',
        ),
        migrations.RemoveField(
            model_name='groupmovielist',
            name='vote_likes',
        ),
        migrations.AddField(
            model_name='groupmovielist',
            name='vote',
            field=models.IntegerField(default=0, verbose_name='vote'),
        ),
    ]
